### PR TITLE
fix-63

### LINKED ISSUE #63: Stuck when switching between Color-Modes
Hi,

I installed the latest update, but now when switching the style the site nothing happens and the new theme is only applied after manually refreshing.

When switching to dark, i get this error in the console:

Refused to apply style from 'https://***.de/admin/undefined' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

when switching back to "normal" no error appears, but also doesnt change from dark to normal theme, unless refreshing the site.

Also i see various CSP errors when the plugin is enabled:
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-vaECDH5NodNv9Hm9Uw5/O5Xq' 'self' https://* http://* * 'unsafe-inline' 'report-sample'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Also not sure if related:
this requests fails, because the file/path doesnt exist.
GET https://**/assets/img/mime/pdf.png 500 (Internal Server Error)

### PR DESCRIPTION
**Pull request by felixhahnweilheim**
fix #63 
by removing the use of `$('head').append()`

### CODE REVIEW

**Review by ArchBlood — CHANGES_REQUESTED** [review]
I believe the code was correct beforehand only issue is with how you are using `publish` and `getAssetPath` that should be fixed as well as making sure that in the switch button itself has a nonce applied (i.e., `Html::nonce()`).

**Review by ArchBlood — CHANGES_REQUESTED** [review]
Works slightly better now than it did before this PR, slight issue on switching though that should be looked into.
Screenshot_1

File: assets/SettingsAsset.php [hunk 1]
```diff
@@ -16,14 +19,14 @@ class SettingsAsset extends AssetBundle
...
-        $url = $am->publish($darkStyleAsset->sourcePath . $am->getAssetPath($darkStyleAsset, $darkStyleAsset->css[0]))[1];
+        $mode = (new UserSetting())->darkMode;
+        if ($mode === UserSetting::OPTION_LIGHT) {
+            DarkStyleLightAsset::register($view);
+        }
         $view->registerJsConfig('dark-mode.switch', [
             'initOnAjaxUrls' => [
                 Url::to(['/dark-mode/user/modal']), // Don't add any params to the URL
-            ],
-            'css-url' => $url
```
Comment (ArchBlood) [inline assets/SettingsAsset.php:26]: I don't see any reason to change this, maybe just add `Html::nonce()` wrapper instead of removing?

Comment (felixhahnweilheim) [reply assets/SettingsAsset.php:26]: It is not needed anymore as the CSS file is loaded via assets.
